name: Create release with ZIP files for datapack and resourcepack

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tag name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set repository name
        run: echo "REPOSITORY=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Create ZIP files
        run: |
          cd datapack && zip -r ../${{ env.REPOSITORY }}-datapack-${{ env.TAG }}.zip * && cd ..
          cd resourcepack && zip -r ../${{ env.REPOSITORY }}-resourcepack-${{ env.TAG }}.zip * && cd ..

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          draft: false
          prerelease: false
          files: |
            ${{ env.REPOSITORY }}-datapack-${{ env.TAG }}.zip
            ${{ env.REPOSITORY }}-resourcepack-${{ env.TAG }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
